name: create and publish docker image
    
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Sanitize repo slug
        uses: actions/github-script@v7
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ github.repository }}'.toLowerCase()
      -
        name: checkout repository
        uses: actions/checkout@v3
      -
        name: set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.repo_slug.outputs.result }}
          